### ISSUE TITLE
Often arrow key not works as expected on web.

### ISSUE THREAD

**Issue by ctoabidmaqbool** [dlsc-software-consulting-gmbh/jfxcentral2#403]
Hi! I am noting arrows keys are not working as expected. 

For example, Click on any menu e.g. `Resources`. Then press the `Ese` button to close the menu.

Now press the keyboard **Up / Down** to scroll the page. You will notes the menu will again open and *next / previous* menu will be selected however Menu was closed by `Esc` button.

![image](https://github.com/dlemmermann/jfxcentral2/assets/10474725/e4ee796b-35c5-44bf-be9a-f5851b5917ea)

Another example, open the `Showcase page`. By using Arrow **Down key**, go to pagination pages number then then Click on **1 page no** as shown. 

![image](https://github.com/dlemmermann/jfxcentral2/assets/10474725/26831772-8775-4281-b566-3777a93ccf24)

Now using **Up arrow key**, scroll to top of the page. After you go to top of the page, press the **Down arrow** couple of times you will notes unexpected things happens as shown:

![image](https://github.com/dlemmermann/jfxcentral2/assets/10474725/8609e77d-456e-4e9a-b11e-1975910403a6)

Let me know if any more info needed or any confusion about my question.

**Comment by leewyatt** [comment]
Thank you for your feedback; you are truly very meticulous. I have already tested, and I was able to reproduce these bugs.

Some of the reasons have been identified. The issue occurs when the ComboBox gains focus and different values are selected using the up and down keys.
<img width="637" alt="1690007921883" src="https://github.com/dlemmermann/jfxcentral2/assets/75261429/0b370048-9ae1-467f-b3f0-846dd92eca31">

**Comment by leewyatt** [comment]
@ctoabidmaqbool Hi.  But I feel that the first issue might not be considered a bug. What do you think? When the MenuButton gains focus, even if the popup is closed using ESC, it still remains in focus and can still be used to navigate the MenuItems using the up and down arrow keys. This behavior is actually a setting in JavaFX.
```java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.MenuButton;
import javafx.scene.control.MenuItem;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;

public class MenuButtonTest extends Application {

    @Override
    public void start(Stage primaryStage) {
        HBox hbox = new HBox(10);

        MenuButton menuButton1 = new MenuButton("Menu Button 1");
        MenuItem menuItem1A = new MenuItem("Item 1A");
        MenuItem menuItem1B = new MenuItem("Item 1B");
        menuButton1.getItems().addAll(menuItem1A, menuItem1B);

        MenuButton menuButton2 = new MenuButton("Menu Button 2");
        MenuItem menuItem2A = new MenuItem("Item 2A");
        MenuItem menuItem2B = new MenuItem("Item 2B");
        menuButton2.getItems().addAll(menuItem2A, menuItem2B);

        hbox.getChildren().addAll(menuButton1, menuButton2);

        Scene scene = new Scene(hbox, 400, 100);
        primaryStage.setScene(scene);
        primaryStage.setTitle("MenuButton Test");
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

**Comment by ctoabidmaqbool** [comment]
@leewyatt If you look like a Javafx developer, then it's looks like not a bug / issue...

But if someone looks website as a general user (he may / may not know that this website is made with javafx using jpro.one plugin) of website, then it looks like issue there.

I often user arrows key to navigate website scrolling, and find issues here and there.

**Comment by leewyatt** [comment]
@ctoabidmaqbool Thank you for your patient explanation. It sounds very reasonable.
