### ISSUE TITLE
Create redirect from https://www.jfx-central.com/home to https://www.jfx-central.com

### ISSUE THREAD

**Issue by FDelporte** [dlsc-software-consulting-gmbh/jfxcentral2#416]
The home url was the automatically redirected page when you hit https://www.jfx-central.com, so I'm afraid I (and others) used it in many places as a link to the website. But V2 shows it as a 404. 

Can we just have a redirect from `/home` to `/`?

**Comment by leewyatt** [comment]
Thank you for your suggestion; 
I've set "/","/home" and "/index" to point to the same webpage; 
![image](https://github.com/dlemmermann/jfxcentral2/assets/75261429/8d6d678c-1139-4fc9-9f6e-452f62971012)

**Comment by dlemmermann** [comment]
Please use startOrRefresh as name for function.
