### ISSUE TITLE
New desktop installer

### ISSUE THREAD

**Issue by dlemmermann** [dlsc-software-consulting-gmbh/jfxcentral2#425]
Hi Mike, please create a new version of the jfxcentral2 installer. We are finally ready to announce it.

**Comment by mikehearn** [comment]
What's the commit ID?

**Comment by dlemmermann** [comment]
Sorry, I forgot our "process" :-) I will get back to you ASAP.

**Comment by dlemmermann** [comment]
Release 3, Tag: v1.1.0

**Comment by mikehearn** [comment]
I will try to get it done today, otherwise next week.

**Comment by mikehearn** [comment]
Done. Unfortunately no delta update for macOS this time. Conveyor 11 will come out in a few days and that will add support for Mac delta updates. So, next time, we'll have that.

**Comment by dlemmermann** [comment]
Thank you!

**Comment by leewyatt** [comment]
> Done. Unfortunately no delta update for macOS this time. Conveyor 11 will come out in a few days and that will add support for Mac delta updates. So, next time, we'll have that.

Thank you ~

**Comment by dlemmermann** [comment]
We need another build of the installer. Release 4, v1.2.0

**Comment by dlemmermann** [comment]
And before you know it we need another one .... Release 5, v1.3.0

**Comment by dlemmermann** [comment]
To align release name and tag number I have created Release 6 and tag v1.6.0. Please use this one for the next installer release.

**Comment by mikehearn** [comment]
Done.

**Comment by dlemmermann** [comment]
Thank you! So next time we get a delta update?

**Comment by mikehearn** [comment]
Yep.
