### ISSUE TITLE
Data update shows incorrect percentages

### ISSUE THREAD

**Issue by FDelporte** [dlsc-software-consulting-gmbh/jfxcentral2#442]
On start of the web and app, while fetching the data, I have seen percentages going up to 120, 200,...
It seems there is some miscalculation going on.

**Comment by leewyatt** [comment]
Thank you for pointing out the issue. This problem was indeed more common in earlier versions. In the recent versions, I haven't observed this issue. However, I will make multiple attempts to reproduce this problem and look into it further.

**Comment by dlemmermann** [comment]
Closing this issue. I am pretty sure that is somewhere deep inside the JGit library and out of scope for fixing by us.
