### ISSUE TITLE
Optimize Image Loading to Prevent UI Freezing

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/jfxcentral2#446]
### Description:

There are currently two scenarios leading to noticeable UI freezes in our application due to image loading:

1. **OpenJFX Page Avatar Loading**: The OpenJFX page contains a large number of avatars. Loading all these images simultaneously can result in a prolonged UI freeze until all avatars are completely loaded.
   
2. **YouTube Video Preview Loading**: In some regions, accessing YouTube is restricted or blocked. Attempts to fetch YouTube video preview images in these regions result in the UI being frozen until the connection times out.

### Implications:

- **Degraded User Experience**: Extended UI freezes significantly affect the responsiveness and usability of our application.
- **Potential Data Access Issues**: In regions where YouTube is inaccessible, users are left waiting for an unnecessary amount of time.

**Comment by leewyatt** [comment]
![image](https://github.com/dlsc-software-consulting-gmbh/jfxcentral2/assets/75261429/ae294457-fb6c-4051-ba3c-0d04fa157f2d)

**Comment by FlorianKirmaier** [comment]
I'm working on a suggestion to improve it.

**Comment by FlorianKirmaier** [comment]
I've made 2 PRs: 
1. https://github.com/dlsc-software-consulting-gmbh/jfxcentral2/pull/447
2. https://github.com/dlsc-software-consulting-gmbh/jfxcentral-data/pull/275

Seems to be working - looks like the "background loading" flag was set to false. Event so most of the code was only about loading in the background.

I've now seen the following exception:
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: ImageView.clip : A bound value cannot be set.
	at javafx.base@20/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:143)
	at javafx.graphics@20/javafx.scene.Node.setClip(Node.java:1545)
	at com.dlsc.jfxcentral2.components/com.dlsc.jfxcentral2.components.skins.AvatarViewSkin.lambda$new$0(AvatarViewSkin.java:37)
```
But I don't know if it's related.

**Comment by dlemmermann** [comment]
I think this has been nicely fixed by @FlorianKirmaier now. Closing the issue.

**Comment by dlemmermann** [comment]
The exception is also fixed. Yes, it was related.
