### ISSUE TITLE
Standardize the Use of GemsFX Spacer Component in the Component Module

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/jfxcentral2#480]
### Issue Description

To prevent confusion and streamline our development process, we plan to standardize the use of the Spacer component by exclusively utilizing the more convenient Spacer component available in the GemsFX library, replacing the current Spacer in the component module.

**Comment by dlemmermann** [comment]
We can do this at any time ... whenever we touch a file that uses a Region for spacing.
