### ISSUE TITLE
Add the Java and JavaFX version to site

### ISSUE THREAD

**Issue by FDelporte** [dlsc-software-consulting-gmbh/jfxcentral2#501]
Maybe something to add in the header? Dynamically generated to be always up-to-date...

"This site runs on Java ?? with JavaFX 21".

**Comment by dlemmermann** [comment]
Done.

<img width="746" alt="Bildschirmfoto 2023-09-28 um 13 44 01" src="https://github.com/dlsc-software-consulting-gmbh/jfxcentral2/assets/9534301/3bd17d6d-6a69-4154-bb95-bf8e78e9c67c">

**Comment by dlemmermann** [comment]
I changed it to a smaller font size.

<img width="695" alt="Bildschirmfoto 2023-09-28 um 13 55 38" src="https://github.com/dlsc-software-consulting-gmbh/jfxcentral2/assets/9534301/7e8ce623-d4dd-4b29-a19a-246f6a968e94">
