### ISSUE TITLE
Integrate video in content

### ISSUE THREAD

**Issue by FDelporte** [dlsc-software-consulting-gmbh/jfxcentral2#508]
Would it be possible to integrate video into some of the content?

Use-case: make e.g. the showcases more attractive.

In this case https://www.jfx-central.com/real_world/deepspace there is a link to a video, but the content itself only contains static images. The strength of JavaFX is animations, charts filling with data, etc. So it would be great to have some way to make the content even more appealing with videos that could show a running application, a voice describing the application, etc.

Maybe with some form of shortcode? In GoHugo markdown this format is used: `{{< youtube Wrx7iVCVTwg >}}` where the code is the ID of the YouTube link.

**Comment by dlemmermann** [comment]
I agree. This would be nice. For this to work the MDFX library from Florian needs to support it. Assigning the ticket to @FlorianKirmaier.

**Comment by FDelporte** [comment]
Has been implemented in JPro and used in the new learn pages.
Thanks @FlorianKirmaier !
