### ISSUE TITLE
New conveyor build

### ISSUE THREAD

**Issue by dlemmermann** [dlsc-software-consulting-gmbh/jfxcentral2#544]
Hi Mike, please create a new version of the conveyor installer. Release 10, Tag: v1.10.0

**Comment by mikehearn** [comment]
Am on the road today but will try and get to it this evening.

**Comment by dlemmermann** [comment]
Thanks!

**Comment by mikehearn** [comment]
Done. Here's the config tweaks required this time:

https://github.com/hydraulic-software/jfxcentral2/commit/f75e567028e651d0c01f99379465d7aa80b1420f

**Comment by dlemmermann** [comment]
Thanks ... but I do not have access to the hydraulic repository.
