### ISSUE TITLE
Learn section: missing button to external link for source code

### ISSUE THREAD

**Issue by FDelporte** [dlsc-software-consulting-gmbh/jfxcentral2#561]
If the Learn object has a value defined for `sourceCodeUrl`, a button should be shown that links to this sources.
Maybe even on top and bottom of the page, with a label like this "Sources are available"?

eg `"sourceCodeUrl": "https://github.com/edwardalgorist/jfx-tutorial/blob/main/src/main/java/com/coderscratchpad/javafxtutorial/BasicGui.java"`

**Comment by dlemmermann** [comment]
@leewyatt I think we can use the detail header button ("website") for this.
