### ISSUE TITLE
Add detail box for "Learn"

### ISSUE THREAD

**Issue by FDelporte** [dlsc-software-consulting-gmbh/jfxcentral2#564]
The people page has links to all the sections in which a person is linked. So we should also link to the Learn-pages.

**Comment by leewyatt** [comment]
> Related to this ticket, should the small-people-box also be extended to list all related items? E.g. Gail Anderson not only has a book on JFX Central, but also learn and company...
> 
> ![Screenshot 2023-11-08 at 09 33 49](https://user-images.githubusercontent.com/1415873/281322839-5e1719fe-5022-4d18-ad64-fbf4918844b1.png)

Thank you for the reminder.
