### ISSUE TITLE
Add introduction text to each section of the site

### ISSUE THREAD

**Issue by FDelporte** [dlsc-software-consulting-gmbh/jfxcentral2#581]
Is there a way (or can we add it) to add an introduction text to each section of JFX Central?
I think that would be a great improvement regarding search indexes...

<img width="1542" alt="Screenshot 2023-12-13 at 08 15 13" src="https://github.com/dlsc-software-consulting-gmbh/jfxcentral2/assets/1415873/39d9a76b-b31d-47e8-a8f8-dc1b0b9ef7f5">

**Comment by dlemmermann** [comment]
Added by Lee.

**Comment by dlemmermann** [comment]
For example "libraries":

<img width="1383" alt="Bildschirmfoto 2023-12-18 um 14 45 09" src="https://github.com/dlsc-software-consulting-gmbh/jfxcentral2/assets/9534301/22ad40b2-f8fa-4713-9e64-948931c3bfec">
