### ISSUE TITLE
New desktop installer, release 14, v1.14.0

### ISSUE THREAD

**Issue by dlemmermann** [dlsc-software-consulting-gmbh/jfxcentral2#593]
We introduced a performance regression with our latest release by using the latest JavaFX release. They meant well, but something went wrong. :-)

**Comment by dlemmermann** [comment]
Would be great to have this available soon as the JFXCentral website will be presented in the German "Java Magazin" in a few days with an 8 page article.

**Comment by dlemmermann** [comment]
https://entwickler.de/java/jfx-central-javafx

**Comment by mikehearn** [comment]
Done.
