### ISSUE TITLE
New video type: JFX In Action

### ISSUE THREAD

**Issue by FDelporte** [dlsc-software-consulting-gmbh/jfxcentral2#605]
Is the list of video types hardcoded are based on the values in the JSON file?
I would need a new type "JFX In Action". Can I add it in the JSON or is a website change needed?

![Screenshot 2024-05-16 at 14 50 55](https://github.com/dlsc-software-consulting-gmbh/jfxcentral2/assets/1415873/de598a55-128d-4e23-902f-446bfe8a52ee)

**Comment by leewyatt** [comment]
@FDelporte Hi Frank, "The 'Type' attribute of Video is sourced from the [videos.json](https://github.com/dlsc-software-consulting-gmbh/jfxcentral-data/blob/staging/videos/videos.json) file. Each Video object in it has a 'type' property."

**Comment by FDelporte** [comment]
Thanks for the explanation @leewyatt ! So that's a ticket we can close easily ;-)

**Comment by FDelporte** [comment]
Hi @leewyatt, I added the first video with this new type, but still it isn't shown in the Types dropdown... Can you take a look please?

https://www.jfx-central.com/videos/YaF62a4pebg

Additional question, should I create a ticket to also be able to link a video to realword? I added 'realworldIds' but they don't show up on the video page.

**Comment by leewyatt** [comment]
Hi @FDelporte,

I tested it on the client and can see the new video type "JFX In Action." When running jpro locally, I can also see the new video category "JFX In Action." However, this newly added category is not visible on the jfxcentral website. I am currently seeking assistance from @FlorianKirmaier regarding this issue.

**Comment by leewyatt** [comment]
@FlorianKirmaier I saw the new type on the website. Thank you very much.

**Comment by FDelporte** [comment]
Thanks!!
