### ISSUE TITLE
Some missing "linking blocks"

### ISSUE THREAD

**Issue by FDelporte** [dlsc-software-consulting-gmbh/jfxcentral2#612]
Most pages contain blocks to visualize a link between that page and another, but some are missing.

For instance:
* [videos with XPipe](https://www.jfx-central.com/videos/mZV1OJ23d2c)
   * Correctly shows libraries and people
   * But in the JSON, also realworldIds are defined, and they don't show up
   ```
   "realworldIds": [
      "xpipe"
    ]
   ```
* maybe there are others like this, but couldn't find example yet

**Comment by dlemmermann** [comment]
But I can see them now ....
